# Generated by Django 3.2 on 2025-09-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengelola',
            fields=[
                ('pengelolaKODE', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('pengelolaPASSWORD', models.CharField(max_length=60)),
                ('pengelolaEMAIL', models.CharField(max_length=255, unique=True)),
                ('pengelolaNAMA1', models.CharField(max_length=60)),
                ('pengelolaNAMA2', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('provinsiKODE', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('provinsiNAMA', models.CharField(max_length=30)),
                ('provinsiKET', models.CharField(blank=True, max_length=255, null=True)),
                ('provinsiALAMAT', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
