# Generated by Django 3.2.25 on 2025-09-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='anggota',
            fields=[
                ('anggotaKODE', models.IntegerField(primary_key=True, serialize=False)),
                ('anggotaNAMA', models.CharField(max_length=60)),
                ('anggotaHP', models.CharField(max_length=15)),
                ('anggotaEMAIL', models.CharField(max_length=60, unique=True)),
                ('anggotaPASSWORD', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'anggota',
            },
        ),
        migrations.AlterModelTable(
            name='pengelola',
            table='pengelola',
        ),
        migrations.AlterModelTable(
            name='provinsi',
            table='provinsi',
        ),
    ]
