# Generated by Django 3.2.25 on 2025-09-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250915_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='kabupaten',
            fields=[
                ('kabupatenKODE', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('kabupatenNAMA', models.CharField(max_length=60)),
                ('kabupatenKET', models.TextField(blank=True, null=True)),
                ('kabupatenALAMAT', models.CharField(blank=True, max_length=255, null=True)),
                ('kabupatenFOTOICON', models.CharField(blank=True, max_length=255, null=True)),
                ('kabupatenFOTOICONKET', models.TextField(blank=True, null=True)),
                ('datecreated', models.DateField(blank=True, null=True)),
                ('dateupdated', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kabupaten',
            },
        ),
        migrations.AddField(
            model_name='provinsi',
            name='datecreated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provinsi',
            name='dateupdated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provinsi',
            name='usercreated',
            field=models.ForeignKey(blank=True, db_column='usercreated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinsi_created', to='app.pengelola'),
        ),
        migrations.AddField(
            model_name='provinsi',
            name='userupdated',
            field=models.ForeignKey(blank=True, db_column='userupdated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinsi_updated', to='app.pengelola'),
        ),
        migrations.CreateModel(
            name='kecamatan',
            fields=[
                ('kecamatanKODE', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('kecamatanNAMA', models.CharField(max_length=30)),
                ('kabupatenALAMAT', models.CharField(blank=True, max_length=255, null=True)),
                ('kecamatanKET', models.TextField(blank=True, null=True)),
                ('datecreated', models.DateField(blank=True, null=True)),
                ('dateupdated', models.DateField(blank=True, null=True)),
                ('kabupatenKODE', models.ForeignKey(blank=True, db_column='kabupatenKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kabupaten')),
                ('usercreated', models.ForeignKey(blank=True, db_column='usercreated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kecamatan_created', to='app.pengelola')),
                ('userupdated', models.ForeignKey(blank=True, db_column='userupdated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kecamatan_updated', to='app.pengelola')),
            ],
            options={
                'db_table': 'kecamatan',
            },
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='provinsiKODE',
            field=models.ForeignKey(blank=True, db_column='provinsiKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.provinsi'),
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='usercreated',
            field=models.ForeignKey(blank=True, db_column='usercreated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kabupaten_created', to='app.pengelola'),
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='userupdated',
            field=models.ForeignKey(blank=True, db_column='userupdated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kabupaten_updated', to='app.pengelola'),
        ),
    ]
