# Generated by Django 3.2.25 on 2025-09-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250918_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kecamatan',
            old_name='kabupatenALAMAT',
            new_name='kecamatanALAMAT',
        ),
    ]
