# Generated by Django 3.2.25 on 2025-09-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_kabupatenalamat_kecamatan_kecamatanalamat'),
    ]

    operations = [
        migrations.CreateModel(
            name='kategoriberita',
            fields=[
                ('kategoriberitaKODE', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('kategoriberitaNAMA', models.CharField(max_length=8)),
                ('kategoriberitaKET', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'kategoriberita',
            },
        ),
        migrations.CreateModel(
            name='kategoriwisata',
            fields=[
                ('kategoriwisataKODE', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('kategoriwisataNAMA', models.CharField(max_length=60)),
                ('kategoriwisataKET', models.TextField(blank=True, null=True)),
                ('kategoriREFERENCE', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'kategoriwisata',
            },
        ),
        migrations.CreateModel(
            name='obyekwisata',
            fields=[
                ('obyekKODE', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('obyekNAMA', models.CharField(max_length=120)),
                ('obyekALAMAT', models.CharField(blank=True, max_length=255, null=True)),
                ('obyekDERAJAT_S', models.IntegerField(blank=True, null=True)),
                ('obyekMENIT_S', models.IntegerField(blank=True, null=True)),
                ('obyekDETIK_S', models.DecimalField(decimal_places=2, max_digits=5)),
                ('obyekLATITUDE', models.DecimalField(decimal_places=11, max_digits=15)),
                ('obyekDERAJAT_E', models.IntegerField(blank=True, null=True)),
                ('obyekMENIT_E', models.IntegerField(blank=True, null=True)),
                ('obyekDETIK_E', models.DecimalField(decimal_places=2, max_digits=5)),
                ('obyekLONGITUDE', models.DecimalField(decimal_places=11, max_digits=15)),
                ('obyekKETINGGIAN', models.IntegerField(blank=True, null=True)),
                ('obyekJAMBUKA', models.TimeField(blank=True, null=True)),
                ('obyekJAMTUTUP', models.TimeField(blank=True, null=True)),
                ('obyekPOPULARITAS', models.IntegerField(blank=True, null=True)),
                ('obyekKEMUDAHAN', models.IntegerField(blank=True, null=True)),
                ('obyekDEFINISI', models.TextField(blank=True, null=True)),
                ('obyekKETERANGAN', models.TextField(blank=True, null=True)),
                ('obyekFOTO', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreated', models.DateField(blank=True, null=True)),
                ('dateupdated', models.DateField(blank=True, null=True)),
                ('kategoriKODE', models.ForeignKey(blank=True, db_column='kaategoriKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kategoriwisata')),
                ('kecamatanKODE', models.ForeignKey(blank=True, db_column='kecamatanKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kecamatan')),
                ('usercreated', models.ForeignKey(blank=True, db_column='usercreated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obyekwisata_created', to='app.pengelola')),
                ('userupdated', models.ForeignKey(blank=True, db_column='userupdated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obyekwisata_updated', to='app.pengelola')),
            ],
            options={
                'db_table': 'obyekwisata',
            },
        ),
        migrations.CreateModel(
            name='kegiatan',
            fields=[
                ('eventKODE', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('eventNama', models.CharField(max_length=255)),
                ('eventKET', models.TextField(blank=True, null=True)),
                ('eventMULAI', models.DateField(blank=True, null=True)),
                ('eventSELESAI', models.DateField(blank=True, null=True)),
                ('eventPOSTER', models.CharField(blank=True, max_length=120, null=True)),
                ('eventSUMBER', models.CharField(blank=True, max_length=120, null=True)),
                ('datecreated', models.DateField(blank=True, null=True)),
                ('dateupdated', models.DateField(blank=True, null=True)),
                ('kabupatenKODE', models.ForeignKey(blank=True, db_column='kabupatenKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kabupaten')),
                ('usercreated', models.ForeignKey(blank=True, db_column='usercreated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kegiatan_created', to='app.pengelola')),
                ('userupdated', models.ForeignKey(blank=True, db_column='userupdated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kegiatan_updated', to='app.pengelola')),
            ],
            options={
                'db_table': 'kegiatan',
            },
        ),
        migrations.CreateModel(
            name='berita',
            fields=[
                ('beritaKODE', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('beritaJUDUL', models.CharField(max_length=255)),
                ('beritaISI', models.TextField(blank=True, null=True)),
                ('beritaISI2', models.TextField(blank=True, null=True)),
                ('beritaSUMBER', models.CharField(blank=True, max_length=255, null=True)),
                ('beritaPENULIS', models.CharField(blank=True, max_length=60, null=True)),
                ('beritaTGL', models.DateField(blank=True, null=True)),
                ('beritaICONFOTO', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreated', models.DateField(blank=True, null=True)),
                ('dateupdated', models.DateField(blank=True, null=True)),
                ('eventKODE', models.ForeignKey(blank=True, db_column='eventKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kegiatan')),
                ('kabupatenKODE', models.ForeignKey(blank=True, db_column='kabupatenKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kabupaten')),
                ('kategoriberitaKODE', models.ForeignKey(blank=True, db_column='kategoriberitaKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kategoriberita')),
                ('obyekKODE', models.ForeignKey(blank=True, db_column='obyekKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.obyekwisata')),
                ('usercreated', models.ForeignKey(blank=True, db_column='usercreated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berita_created', to='app.pengelola')),
                ('userupdated', models.ForeignKey(blank=True, db_column='userupdated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berita_updated', to='app.pengelola')),
            ],
            options={
                'db_table': 'berita',
            },
        ),
    ]
