# Generated by Django 3.2.25 on 2025-09-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_berita_kategoriberita_kategoriwisata_kegiatan_obyekwisata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriberita',
            name='kategoriberitaKET',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kategoriberita',
            name='kategoriberitaNAMA',
            field=models.CharField(max_length=60),
        ),
    ]
