# Generated by Django 3.2.25 on 2025-09-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20250919_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obyekwisata',
            name='obyekDETIK_E',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='obyekwisata',
            name='obyekDETIK_S',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='obyekwisata',
            name='obyekLATITUDE',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='obyekwisata',
            name='obyekLONGITUDE',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True),
        ),
    ]
