# Generated by Django 3.2.25 on 2025-09-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20250919_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obyekwisata',
            name='kategoriKODE',
            field=models.ForeignKey(blank=True, db_column='kategoriKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kategoriwisata'),
        ),
    ]
