# Generated by Django 3.2.25 on 2025-09-23 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_obyekwisata_kategorikode'),
    ]

    operations = [
        migrations.CreateModel(
            name='jarakobyek',
            fields=[
                ('ruteKODE', models.IntegerField(primary_key=True, serialize=False)),
                ('obyekjarak', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('obyektempuh', models.IntegerField(blank=True, null=True)),
                ('obyekrute', models.TextField(blank=True, null=True)),
                ('obyekKODEasal', models.ForeignKey(blank=True, db_column='obyekKODEasal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obyekKODEasal', to='app.obyekwisata')),
                ('obyekKODEtujuan', models.ForeignKey(blank=True, db_column='obyekKODEtujuan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obyekKODEtujuan', to='app.obyekwisata')),
            ],
            options={
                'db_table': 'jarakobyek',
            },
        ),
    ]
