# Generated by Django 3.2.25 on 2025-09-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_jarakobyek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kegiatan',
            old_name='eventNama',
            new_name='eventNAMA',
        ),
    ]
