# Generated by Django 5.2.6 on 2025-09-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_eventnama_kegiatan_eventnama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kabupaten',
            name='kabupatenNAMA',
        ),
    ]
