# Generated by Django 5.2.6 on 2025-09-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_kabupaten_kabupatennama'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabupaten',
            name='kabupatenNAMA',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
