# Generated by Django 3.2.25 on 2025-10-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_kabupaten_kabupatennama'),
    ]

    operations = [
        migrations.AddField(
            model_name='obyekwisata',
            name='obyekWAKTUKUNJUNG',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
