# Generated by Django 5.2.6 on 2025-10-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_obyekwisata_obyekwaktukunjung'),
    ]

    operations = [
        migrations.CreateModel(
            name='hasilitinerary',
            fields=[
                ('hasilKODE', models.AutoField(primary_key=True, serialize=False)),
                ('rute', models.TextField(blank=True, null=True)),
                ('jumlahJARAK', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jumlahWAKTU', models.IntegerField(blank=True, null=True)),
                ('cant_visit_destination', models.TextField(blank=True, null=True)),
                ('datecreated', models.DateField(blank=True, null=True)),
                ('anggotaKODE', models.ForeignKey(blank=True, db_column='anggotaKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anggotaKODEitinerary', to='app.anggota')),
            ],
            options={
                'db_table': 'hasilitinerary',
            },
        ),
    ]
