# Generated by Django 3.2.25 on 2025-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_hasilitinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jarakobyek',
            name='obyekjarak',
        ),
        migrations.AlterField(
            model_name='jarakobyek',
            name='obyektempuh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
