# Generated by Django 5.2.6 on 2025-10-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20251009_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasilitinerary',
            name='jumlahJARAK',
        ),
        migrations.AlterField(
            model_name='hasilitinerary',
            name='jumlahWAKTU',
            field=models.TextField(blank=True, null=True),
        ),
    ]
