# Generated by Django 3.2 on 2025-10-18 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_hasilitinerary_jumlahjarak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasilitinerary',
            name='cant_visit_destination',
        ),
        migrations.RemoveField(
            model_name='hasilitinerary',
            name='jumlahWAKTU',
        ),
        migrations.RemoveField(
            model_name='hasilitinerary',
            name='rute',
        ),
        migrations.AddField(
            model_name='hasilitinerary',
            name='jam_mulai',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilitinerary',
            name='jam_selesai',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilitinerary',
            name='judul_itinerary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='skipitinerary',
            fields=[
                ('skipKODE', models.AutoField(primary_key=True, serialize=False)),
                ('hasilKODE', models.ForeignKey(blank=True, db_column='hasilitinerary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skiphasilitinerary', to='app.hasilitinerary')),
                ('obyekKODE', models.ForeignKey(blank=True, db_column='skipobyekKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.obyekwisata')),
            ],
            options={
                'db_table': 'skipitinerary',
            },
        ),
        migrations.CreateModel(
            name='headeritinerary',
            fields=[
                ('headerKODE', models.AutoField(primary_key=True, serialize=False)),
                ('hari', models.IntegerField(blank=True, null=True)),
                ('jam_mulai', models.TimeField(blank=True, null=True)),
                ('jam_selesai', models.TimeField(blank=True, null=True)),
                ('hasilKODE', models.ForeignKey(blank=True, db_column='hasilitinerary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hasilitineraryheader', to='app.hasilitinerary')),
            ],
            options={
                'db_table': 'headeritinerary',
            },
        ),
        migrations.CreateModel(
            name='detailitinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.IntegerField(blank=True, null=True)),
                ('jam_mulai', models.TimeField(blank=True, null=True)),
                ('jam_selesai', models.TimeField(blank=True, null=True)),
                ('headerKODE', models.ForeignKey(blank=True, db_column='headerKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailheaderKODE', to='app.headeritinerary')),
                ('obyekKODEasal', models.ForeignKey(blank=True, db_column='obyekKODEasal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailobyekKODEasal', to='app.obyekwisata')),
                ('obyekKODEtujuan', models.ForeignKey(blank=True, db_column='obyekKODEtujuan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailobyekKODEtujuan', to='app.obyekwisata')),
            ],
            options={
                'db_table': 'detailitinerary',
            },
        ),
    ]
