# Generated by Django 5.2.6 on 2025-10-18 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20251018_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headeritinerary',
            name='hasilKODE',
            field=models.ForeignKey(blank=True, db_column='hasilKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hasilitineraryheader', to='app.hasilitinerary'),
        ),
        migrations.AlterField(
            model_name='skipitinerary',
            name='hasilKODE',
            field=models.ForeignKey(blank=True, db_column='hasilKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skiphasilitinerary', to='app.hasilitinerary'),
        ),
    ]
