# Generated by Django 3.2 on 2025-10-18 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_headeritinerary_hasilkode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipitinerary',
            name='obyekKODE',
            field=models.ForeignKey(blank=True, db_column='obyekKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.obyekwisata'),
        ),
    ]
