# Generated by Django 3.2 on 2025-10-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_skipitinerary_obyekkode'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailitinerary',
            name='detailKODE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='detailitinerary',
            constraint=models.UniqueConstraint(fields=('obyekKODEasal', 'obyekKODEtujuan', 'headerKODE', 'urutan'), name='unique_detail_itinerary'),
        ),
        migrations.AddConstraint(
            model_name='headeritinerary',
            constraint=models.UniqueConstraint(fields=('hasilKODE', 'hari'), name='unique_header_hasil_hari'),
        ),
        migrations.AddConstraint(
            model_name='skipitinerary',
            constraint=models.UniqueConstraint(fields=('obyekKODE', 'hasilKODE'), name='unique_skip_obyek'),
        ),
    ]
