# Generated by Django 3.2 on 2025-10-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20251020_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detailitinerary',
        ),
    ]
