# Generated by Django 3.2 on 2025-10-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_detailitinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailitinerary',
            fields=[
                ('detailKODE', models.AutoField(primary_key=True, serialize=False)),
                ('urutan', models.IntegerField(blank=True, null=True)),
                ('jam_mulai', models.TimeField(blank=True, null=True)),
                ('jam_selesai', models.TimeField(blank=True, null=True)),
                ('headerKODE', models.ForeignKey(blank=True, db_column='headerKODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailheaderKODE', to='app.headeritinerary')),
                ('obyekKODEasal', models.ForeignKey(blank=True, db_column='obyekKODEasal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailobyekKODEasal', to='app.obyekwisata')),
                ('obyekKODEtujuan', models.ForeignKey(blank=True, db_column='obyekKODEtujuan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailobyekKODEtujuan', to='app.obyekwisata')),
            ],
            options={
                'db_table': 'detailitinerary',
            },
        ),
        migrations.AddConstraint(
            model_name='detailitinerary',
            constraint=models.UniqueConstraint(fields=('obyekKODEasal', 'obyekKODEtujuan', 'headerKODE', 'urutan'), name='unique_detail_itinerary'),
        ),
    ]
