# Generated by Django 5.2.6 on 2025-10-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20251020_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilitinerary',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
