# Generated by Django 5.2.6 on 2025-10-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_hasilitinerary_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilitinerary',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
