# Generated by Django 5.2.6 on 2025-11-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_hasilitinerary_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilitinerary',
            name='hari_input',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
